version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/public/onlinefs_public/src/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
